title: My Personal Website
description: Welcome to my personal website where I share my projects, blog posts, and more about myself.
baseurl: ""
url: "https://alrzakh.github.io"
author: Your Name
email: your.email@example.com
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - .gitattributes
  - .editorconfig
  - .vscode
  - .github
  - vendor
  - node_modules