title: My Personal Website
description: Welcome to my personal website where I share my projects, blog posts, and more about myself.
baseurl: ""
url: "https://alrzakh.github.io"
author: Alireza Khodaie
email: akhodaie22@ku.edu.tr
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - .gitattributes
  - .editorconfig
  - .vscode
  - .github
  - _drafts
  - _posts
  - _data
  - _sass
  - assets
  - pages
  - _includes
  - _layouts
  - CNAME
  - robots.txt